---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hnc.fullname" . }}
  labels:
    {{- include "hnc.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,post-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hnc.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hnc.fullname" . }}
  namespace: {{ .Release.Namespace }}
