apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hnc.fullname" . }}
  labels:
    {{- include "hnc.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,post-delete
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
